[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "pyth-contract"

[dependencies]
ownership = { path = "../libraries/ownership" }
pyth_interface = { path = "../libraries/pyth-interface" }
src5 = { path = "../libraries/src5" }
wormhole_light = { path = "../libraries/wormhole-light" }
