[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "pyth-contract"

[dependencies]
ownership = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.14.0" }
src_5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.1" }
