[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "interface.sw"
license = "Apache-2.0"
name = "pyth-interface"

[dependencies]
src_5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.1" }
